In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from tensorflow.keras.applications import EfficientNetV2B0
from tensorflow.keras import layers, models


In [ ]:

base_model = EfficientNetV2B0(
    weights='imagenet', 
    input_shape=(128, 128, 3), 
    include_top=False
)

base_model.trainable = False

In [ ]:
model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(), # Replacing Flatten() with GlobalAveragePooling2D for better efficiency
    layers.BatchNormalization(),     
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.3),              
    layers.Dense(38, activation='softmax') 
])

In [4]:
training_set = tf.keras.utils.image_dataset_from_directory(
    'D:\\Plant Disease Classifier\\New Plant Diseases Dataset(Augmented)\\New Plant Diseases Dataset(Augmented)\\train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 70295 files belonging to 38 classes.


In [5]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    'D:\\Plant Disease Classifier\\New Plant Diseases Dataset(Augmented)\\New Plant Diseases Dataset(Augmented)\\valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)



Found 17572 files belonging to 38 classes.


In [6]:
training_set

<BatchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [7]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[ 92.25  84.75  86.25]
   [ 87.    79.5   81.  ]
   [ 86.75  78.75  80.75]
   ...
   [ 98.25  90.    94.25]
   [ 99.5   91.25  95.5 ]
   [ 98.25  90.    94.25]]

  [[169.   160.   163.  ]
   [169.75 160.75 163.75]
   [169.5  160.5  163.5 ]
   ...
   [195.25 186.25 191.25]
   [194.5  185.5  190.5 ]
   [191.75 182.75 187.75]]

  [[169.75 160.75 163.75]
   [177.   168.   171.  ]
   [172.75 163.75 166.75]
   ...
   [189.5  180.5  185.5 ]
   [187.25 178.25 183.25]
   [187.5  178.5  183.5 ]]

  ...

  [[135.75 124.75 128.75]
   [139.75 128.75 132.75]
   [126.5  115.5  119.5 ]
   ...
   [186.5  179.5  186.5 ]
   [190.75 183.75 190.75]
   [186.25 179.25 186.25]]

  [[133.5  122.5  126.5 ]
   [137.75 126.75 130.75]
   [126.75 115.75 119.75]
   ...
   [186.5  179.5  186.5 ]
   [194.25 187.25 194.25]
   [192.5  185.5  192.5 ]]

  [[136.75 125.75 129.75]
   [123.5  112.5  116.5 ]
   [116.5  105.5  109.5 ]
   ...
   [191.5  184.5  191.5 ]
   [186.75 179.75 186.75]
   [184.25 177.25 18

In [ ]:

base_model.trainable = True

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [ ]:
history = model.fit(
    training_set,
    validation_data=validation_set,
    epochs=10
)

Epoch 1/10


2197/2197 [==============================] - 405s 177ms/step - loss: 2.4965 - accuracy: 0.3653 - val_loss: 0.8505 - val_accuracy: 0.8028
Epoch 2/10
2197/2197 [==============================] - 386s 176ms/step - loss: 0.7280 - accuracy: 0.8002 - val_loss: 0.2759 - val_accuracy: 0.9247
Epoch 3/10
2197/2197 [==============================] - 400s 182ms/step - loss: 0.3430 - accuracy: 0.9017 - val_loss: 0.1355 - val_accuracy: 0.9612
Epoch 4/10
2197/2197 [==============================] - 394s 179ms/step - loss: 0.2077 - accuracy: 0.9380 - val_loss: 0.0853 - val_accuracy: 0.9737
Epoch 5/10
2197/2197 [==============================] - 356s 162ms/step - loss: 0.1459 - accuracy: 0.9560 - val_loss: 0.0611 - val_accuracy: 0.9809
Epoch 6/10
2197/2197 [==============================] - 348s 158ms/step - loss: 0.1063 - accuracy: 0.9679 - val_loss: 0.0460 - val_accuracy: 0.9856
Epoch 7/10
2197/2197 [==============================] - 7385s 3s/step - loss: 0.0801 - accuracy: 0.9755 - val_loss: 0.0377 