In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
training_set = tf.keras.utils.image_dataset_from_directory(
    'D:\\Plant Disease Classifier\\New Plant Diseases Dataset(Augmented)\\New Plant Diseases Dataset(Augmented)\\train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 70295 files belonging to 38 classes.


In [3]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    'D:\\Plant Disease Classifier\\New Plant Diseases Dataset(Augmented)\\New Plant Diseases Dataset(Augmented)\\valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)



Found 17572 files belonging to 38 classes.


In [4]:
training_set

<BatchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [5]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[191.5  186.5  192.5 ]
   [192.75 187.75 193.75]
   [192.75 187.75 193.75]
   ...
   [179.   173.   175.  ]
   [180.5  174.5  176.5 ]
   [176.5  170.5  172.5 ]]

  [[194.25 189.25 195.25]
   [194.25 189.25 195.25]
   [193.   188.   194.  ]
   ...
   [178.25 172.25 174.25]
   [178.25 172.25 174.25]
   [176.25 170.25 172.25]]

  [[197.   192.   198.  ]
   [197.   192.   198.  ]
   [195.25 190.25 196.25]
   ...
   [179.5  173.5  175.5 ]
   [176.5  170.5  172.5 ]
   [178.25 172.25 174.25]]

  ...

  [[ 65.75  85.    62.25]
   [ 79.5   99.5   73.25]
   [ 71.5   92.75  60.  ]
   ...
   [ 55.75  68.75  49.25]
   [ 69.25  82.    65.5 ]
   [119.   131.   117.  ]]

  [[ 57.25  79.75  55.25]
   [ 64.    87.    59.  ]
   [ 77.   101.25  65.5 ]
   ...
   [ 67.75  80.5   64.  ]
   [ 90.75 102.75  90.25]
   [ 99.75 111.75 100.75]]

  [[ 71.5   94.    69.5 ]
   [ 70.25  93.75  63.75]
   [ 78.25 102.75  64.75]
   ...
   [ 76.5   88.5   74.5 ]
   [ 73.    85.    74.5 ]
   [100.   111.   10

In [6]:
from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D,Flatten,Dropout
from tensorflow.keras.models import Sequential

In [7]:
model = Sequential()

In [8]:
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=32,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [ ]:
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=64,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))